version: '3.9'

services: 
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://user:password@db:5432/delivery_app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: delivery_app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  json-server:
    container_name: json-server
    build:
      context: ./json-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./json-server/db.json:/app/db.json

volumes:
  db_data:
